/// Flutter icons PipocaBasics
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PipocaBasics
///      fonts:
///       - asset: fonts/PipocaBasics.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class PipocaBasics {
  PipocaBasics._();

  static const _kFontFam = 'PipocaBasics';
  static const  _kFontPkg = null;

  static const IconData quill = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dharma_wheel = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_arrow = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compare_arrows = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popcorn = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData party = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
